runtime: custom
env: flex
##entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 2
  cpu_utilization:
    target_utilization: 0.8

