### 1. Get Linux
FROM python

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Setup locale. This prevents Python 3 IO encoding issues.
ENV LANG C.UTF-8
# Make stdout/stderr unbuffered. This prevents delay between output and cloud
# logging collection.
ENV PYTHONUNBUFFERED 1

#RUN virtualenv /env -p python3
# Set virtualenv environment variables. This is equivalent to running
# source /env/bin/activate.
#ENV VIRTUAL_ENV /env
#ENV PATH /env/bin:$PATH
##ENV PATH /opt/conda/bin:$PATH

RUN apt-get -y update && apt-get -y install gcc cmake build-essential
RUN apt-get -y install ffmpeg libsm6 libxext6   
RUN apt-get -y install pkg-config 
RUN apt-get -y install poppler-utils

### RUN pip install --trusted-host pypi.python.org flask
COPY ./ /app/.
WORKDIR /app

RUN pip install --upgrade pip

RUN pip install -r requirements.txt
# install libs

#RUN pip install torch==1.11.0+cpu torchvision==0.12.0+cpu torchaudio==0.11.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
RUN pip install 'git+https://github.com/facebookresearch/detectron2.git'
#RUN pip install layoutparser "layoutparser[ocr]"
#RUN pip install "camelot-py[base]"
#RUN pip install pdf2doi

#ENV FLASK_APP main.py
#ENV FLASK_RUN_HOST 0.0.0.0
#ENV FLASK_RUN_PORT 8080
EXPOSE 8080
#ENV PORT 8080

#CMD ["python3", "test.py"]
ENTRYPOINT gunicorn -b :$PORT test:app --timeout 3000 